name: Trigger Render Deployment
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: srv-cq7lqb6ehbks7391fngg
          apiKey: rnd_0aFxnJdWc42eJOfBTubJGjBkrqEM
          multipleDeployment: false #optional, default true
